name: egresocovid19
description: Aplicación para la gestión de la información de las personas que han sufrido la pandemia del COVID-19.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  beamer:
    git:
      url: https://github.com/slovnicki/beamer.git
      path: package
      ref: 2015b04c79bf139d2df32ea62cba9f5d489433b2
  bloc: ^7.2.1
  dio: ^4.0.0
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  flutter_lyform: ^0.1.2+3
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^0.0.11
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.1.0
  lyform: ^0.3.1+3
  lyform_validators: ^0.2.3+2
  multi_select_flutter: ^4.0.0
  oauth_dio: ^0.2.6
  path_provider: ^2.0.5
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^2.0.1
  rxdart: ^0.27.2
  shared_preferences: ^2.0.8
  smartstruct: ^1.2.3+1

dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  injectable_generator: ^1.5.2
  json_serializable: ^5.0.2
  lint: ^1.7.2
  retrofit_generator: ^2.0.1+1
  smartstruct_generator: ^1.2.3+1

flutter:
  uses-material-design: true

flutter_icons:
  android: 'launcher_icon'
  adaptive_icon_background: 'assets/icon/background.png'
  adaptive_icon_foreground: 'assets/icon/foreground.png'
  ios: false
  image_path: 'assets/icon/icon.jpg'
