name: egresocovid19
description: Aplicación para la gestión de la información de las personas que han sufrido la pandemia del COVID-19.

publish_to: 'none'

version: 0.1.2+3

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  beamer: ^1.2.0
  bloc: ^8.0.2
  dio: ^4.0.4
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_lyform: ^0.5.2
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^0.0.13
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  lyform: ^0.6.1
  lyform_validators: ^0.5.1
  multi_select_flutter: ^4.0.0
  oauth_dio: ^0.2.7
  path_provider: ^2.0.8
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.12

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  lint: ^1.8.2
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: 'launcher_icon'
  adaptive_icon_background: 'assets/icon/background.png'
  adaptive_icon_foreground: 'assets/icon/foreground.png'
  ios: false
  image_path: 'assets/icon/icon.png'

flutter_native_splash:
  color: '#2196F3'
  image: assets/icon/splash.png
  android12: true
