name: deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter format .
      - run: flutter analyze --fatal-infos
      - run: flutter test
      - uses: erickzanardo/flutter-gh-pages@v6
        with:
          targetBranch: deploy
          webRenderer: html
          customArgs: --base-href="/${{ github.event.repository.name }}/"
  gen404:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: deploy
      - uses: canastro/copy-file-action@master
        with:
          source: index.html
          target: 404.html
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: deploy