name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: deploy
          webRenderer: html
          customArgs: --base-href="/${{ github.event.repository.name }}/"
  gen404:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy
      - uses: canastro/copy-action@0.0.2
        with:
          source: index.html
          target: 404.html
      - uses: stefanzweifel/git-auto-commit-action@v4
